apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
spec:
  accessModes: ["ReadWriteMany"]
  capacity:
    storage: 2Gi
  hostPath:
    path: "/data/wp"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pvc
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 2Gi
